import type { ExperienceItem } from '@/types/experience';

export const EXPERIENCE_DATA: ExperienceItem[] = [
	{
		id: '1',
		company: 'Startise',
		position: 'Frontend Engineer',
		startDate: '2024-06',
		location: 'Mirpur DOHS, Dhaka 1206, Bangladesh',
		type: 'Full-time',
		description: 'Startise is the dynamic parent company of WPDeveloper & many other subsidiaries which helps million to start, evolve and get success.',
		responsibilities: [
			'Developed and maintained the frontend for Templately landing pages, admin application, and WordPress plugin',
			'Built responsive UI components using React.js, Next.js, and Tailwind CSS',
			'Integrated frontend applications with REST and GraphQL APIs',
			'Collaborated with design and backend teams to deliver scalable user interfaces',
			'Architected and developed the complete frontend structure for XCloud v1',
			'Built reusable components and managed application state using React and Redux',
		],
		technologies: ['React.js', 'Next.js', 'Redux.js', 'JavaScript', 'TypeScript', 'WordPress', 'Node.js', 'Tailwind CSS', 'MySQL', 'MongoDB', 'Vue.js', 'Laravel', 'PHP', 'GraphQL'],
		achievements: [
			'Contributed to the development of Templately across web app, landing pages, and WordPress plugin',
			'Built and launched the frontend architecture for XCloud v1',
			'Delivered multiple product features and improvements',
			'Improved maintainability through reusable components and structured code',
		],
	},
	{
		id: '2',
		company: 'TubeOnAI',
		position: 'Frontend Developer',
		startDate: '2023-11',
		endDate: '2024-05',
		location: 'Remote',
		type: 'Part-time',
		description:
			'TubeOnAI is an AI platform that summarizes and repurposes videos, podcasts, PDFs, and articles into clear, actionable content. As a Frontend Developer, I worked on the Next.js web app, building UI components, integrating APIs, and ensuring a smooth, responsive experience across devices.',
		responsibilities: [
			'Developed and maintained the TubeOnAI web application using Next.js, TypeScript, and Tailwind CSS',
			'Implemented scalable data fetching and caching using React Query',
			'Built complex forms with validation using React Hook Form and Zod',
			'Integrated Firebase services for authentication and backend interactions',
			'Implemented audio playback features using React Modern Audio Player',
			'Monitored and improved application stability using Sentry',
		],
		technologies: ['TypeScript', 'Next.js', 'Tailwind CSS', 'React Query', 'Zod', 'Firebase', 'React Hook Form', 'React Modern Audio Player', 'Sentry'],
		achievements: [
			'Delivered key frontend features for the TubeOnAI web application',
			'Improved application reliability through error monitoring and debugging with Sentry',
			'Built reusable UI and form components to accelerate development',
			'Optimized data fetching and state management using React Query',
		],
	},
	{
		id: '3',
		company: 'WPDeveloper',
		position: 'Frontend Developer',
		startDate: '2020-11',
		endDate: '2024-05',
		location: 'Mirpur DOHS, Dhaka 1206, Bangladesh',
		type: 'Full-time',
		description: 'WPDeveloper is WordPress-based product company. With 6 million+ happy users from 180+ countries, the company is powering up WordPress web building experience.',
		responsibilities: [
			'Developed and maintained admin interfaces for multiple WordPress plugins including BetterDocs, NotificationX, SchedulePress, and BetterLinks',
			'Built interactive dashboards and analytics visualizations using React.js and ApexCharts',
			'Re-architected complex admin panels and implemented structured UI workflows',
			'Developed rich text editing and content-building features using Draft.js and internal builders',
			'Integrated REST APIs and optimized data handling using React Query, Axios, and Redux',
			'Contributed to the WPDeveloper user dashboard for license management and product access',
		],
		technologies: ['React.js', 'Next.js', 'Redux.js', 'JavaScript', 'TypeScript', 'MySQL', 'PHP', 'GraphQL', 'Wordpress', 'Webpack'],
		achievements: [
			'Contributed to several widely used WordPress plugins across documentation, marketing, scheduling, and link management',
			'Re-architected the BetterDocs admin panel and built its analytics dashboard and FAQ Builder',
			'Established the frontend foundation for BetterLinks and implemented analytics views',
			'Improved admin usability and workflows across multiple plugin interfaces',
			'Delivered scalable React-based admin systems for complex WordPress products',
		],
	},
	{
		id: '4',
		company: 'Easy.Jobs',
		position: 'Junior Frontend Developer',
		startDate: '2020-02',
		endDate: '2020-10',
		location: 'Mirpur DOHS, Dhaka 1206, Bangladesh',
		type: 'Internship',
		description: 'Easy.Jobs is an AI Recruiting Software for Startups to Enterprises was never this fun. easy.jobs is your all-in-one recruitment SaaS tool for career page & ATS.',
		responsibilities: [
			'Developed the frontend for easy.jobs using Vue.js, Bootstrap, and SCSS',
			'Built responsive UI components and interactive dashboards with ApexCharts',
			'Integrated backend APIs and optimized data handling using Axios and Lodash',
			'Collaborated with backend and product teams to implement scalable recruitment workflows',
			'Maintained and improved existing frontend code for performance and usability',
		],
		technologies: ['Software as a Service (SaaS)', 'MySQL', 'Vue.js', 'Laravel', 'PHP', 'JavaScript', 'Application Development'],
		achievements: [
			'Delivered the first frontend implementation for the easy.jobs SaaS platform',
			'Built interactive dashboards and career site interfaces for clients',
			'Improved development efficiency by implementing reusable Vue.js components',
			'Contributed to a scalable frontend structure to support automated recruitment features',
		],
	},
];
